// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $about from "./routes/about.tsx";
import * as $api_gaming_news from "./routes/api/gaming-news.ts";
import * as $api_joke from "./routes/api/joke.ts";
import * as $blog from "./routes/blog.tsx";
import * as $blog_slug_ from "./routes/blog/[slug].tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $news from "./routes/news.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $FeaturedGameNews from "./islands/FeaturedGameNews.tsx";
import * as $MobileMenu from "./islands/MobileMenu.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/about.tsx": $about,
    "./routes/api/gaming-news.ts": $api_gaming_news,
    "./routes/api/joke.ts": $api_joke,
    "./routes/blog.tsx": $blog,
    "./routes/blog/[slug].tsx": $blog_slug_,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/news.tsx": $news,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/FeaturedGameNews.tsx": $FeaturedGameNews,
    "./islands/MobileMenu.tsx": $MobileMenu,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
